# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import ai_core_pb2 as proto_dot_ai__core__pb2


class AICoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Complete = channel.unary_unary(
                '/ai_core.AICore/Complete',
                request_serializer=proto_dot_ai__core__pb2.CompletionRequest.SerializeToString,
                response_deserializer=proto_dot_ai__core__pb2.CompletionResponse.FromString,
                )
        self.StreamComplete = channel.unary_stream(
                '/ai_core.AICore/StreamComplete',
                request_serializer=proto_dot_ai__core__pb2.CompletionRequest.SerializeToString,
                response_deserializer=proto_dot_ai__core__pb2.CompletionChunk.FromString,
                )
        self.Embed = channel.unary_unary(
                '/ai_core.AICore/Embed',
                request_serializer=proto_dot_ai__core__pb2.EmbedRequest.SerializeToString,
                response_deserializer=proto_dot_ai__core__pb2.EmbedResponse.FromString,
                )
        self.Summarize = channel.unary_unary(
                '/ai_core.AICore/Summarize',
                request_serializer=proto_dot_ai__core__pb2.SummarizeRequest.SerializeToString,
                response_deserializer=proto_dot_ai__core__pb2.SummarizeResponse.FromString,
                )


class AICoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Complete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Embed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Summarize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AICoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Complete': grpc.unary_unary_rpc_method_handler(
                    servicer.Complete,
                    request_deserializer=proto_dot_ai__core__pb2.CompletionRequest.FromString,
                    response_serializer=proto_dot_ai__core__pb2.CompletionResponse.SerializeToString,
            ),
            'StreamComplete': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamComplete,
                    request_deserializer=proto_dot_ai__core__pb2.CompletionRequest.FromString,
                    response_serializer=proto_dot_ai__core__pb2.CompletionChunk.SerializeToString,
            ),
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=proto_dot_ai__core__pb2.EmbedRequest.FromString,
                    response_serializer=proto_dot_ai__core__pb2.EmbedResponse.SerializeToString,
            ),
            'Summarize': grpc.unary_unary_rpc_method_handler(
                    servicer.Summarize,
                    request_deserializer=proto_dot_ai__core__pb2.SummarizeRequest.FromString,
                    response_serializer=proto_dot_ai__core__pb2.SummarizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_core.AICore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AICore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai_core.AICore/Complete',
            proto_dot_ai__core__pb2.CompletionRequest.SerializeToString,
            proto_dot_ai__core__pb2.CompletionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ai_core.AICore/StreamComplete',
            proto_dot_ai__core__pb2.CompletionRequest.SerializeToString,
            proto_dot_ai__core__pb2.CompletionChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai_core.AICore/Embed',
            proto_dot_ai__core__pb2.EmbedRequest.SerializeToString,
            proto_dot_ai__core__pb2.EmbedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Summarize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai_core.AICore/Summarize',
            proto_dot_ai__core__pb2.SummarizeRequest.SerializeToString,
            proto_dot_ai__core__pb2.SummarizeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
