# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import ai_core_pb2 as proto_dot_ai__core__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/ai_core_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AICoreStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Complete = channel.unary_unary(
                '/ai_core.AICore/Complete',
                request_serializer=proto_dot_ai__core__pb2.CompletionRequest.SerializeToString,
                response_deserializer=proto_dot_ai__core__pb2.CompletionResponse.FromString,
                _registered_method=True)
        self.StreamComplete = channel.unary_stream(
                '/ai_core.AICore/StreamComplete',
                request_serializer=proto_dot_ai__core__pb2.CompletionRequest.SerializeToString,
                response_deserializer=proto_dot_ai__core__pb2.CompletionChunk.FromString,
                _registered_method=True)
        self.Embed = channel.unary_unary(
                '/ai_core.AICore/Embed',
                request_serializer=proto_dot_ai__core__pb2.EmbedRequest.SerializeToString,
                response_deserializer=proto_dot_ai__core__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.Summarize = channel.unary_unary(
                '/ai_core.AICore/Summarize',
                request_serializer=proto_dot_ai__core__pb2.SummarizeRequest.SerializeToString,
                response_deserializer=proto_dot_ai__core__pb2.SummarizeResponse.FromString,
                _registered_method=True)


class AICoreServicer:
    """Missing associated documentation comment in .proto file."""

    def Complete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Embed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Summarize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AICoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Complete': grpc.unary_unary_rpc_method_handler(
                    servicer.Complete,
                    request_deserializer=proto_dot_ai__core__pb2.CompletionRequest.FromString,
                    response_serializer=proto_dot_ai__core__pb2.CompletionResponse.SerializeToString,
            ),
            'StreamComplete': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamComplete,
                    request_deserializer=proto_dot_ai__core__pb2.CompletionRequest.FromString,
                    response_serializer=proto_dot_ai__core__pb2.CompletionChunk.SerializeToString,
            ),
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=proto_dot_ai__core__pb2.EmbedRequest.FromString,
                    response_serializer=proto_dot_ai__core__pb2.EmbedResponse.SerializeToString,
            ),
            'Summarize': grpc.unary_unary_rpc_method_handler(
                    servicer.Summarize,
                    request_deserializer=proto_dot_ai__core__pb2.SummarizeRequest.FromString,
                    response_serializer=proto_dot_ai__core__pb2.SummarizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_core.AICore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_core.AICore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AICore:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_core.AICore/Complete',
            proto_dot_ai__core__pb2.CompletionRequest.SerializeToString,
            proto_dot_ai__core__pb2.CompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai_core.AICore/StreamComplete',
            proto_dot_ai__core__pb2.CompletionRequest.SerializeToString,
            proto_dot_ai__core__pb2.CompletionChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_core.AICore/Embed',
            proto_dot_ai__core__pb2.EmbedRequest.SerializeToString,
            proto_dot_ai__core__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Summarize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_core.AICore/Summarize',
            proto_dot_ai__core__pb2.SummarizeRequest.SerializeToString,
            proto_dot_ai__core__pb2.SummarizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
