export enum UserErrorCode {
  AUTH_ACCOUNT_NOT_FOUND = 'AUTH_ACCOUNT_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',
  USER_PREFERENCES_NOT_FOUND = 'USER_PREFERENCES_NOT_FOUND',
  TENANT_ACCESS_DENIED = 'TENANT_ACCESS_DENIED',
  KEYCLOAK_SYNC_FAILED = 'KEYCLOAK_SYNC_FAILED',
  RESERVED_ROLE_BLOCKED = 'RESERVED_ROLE_BLOCKED',
}

export enum UserSuccessCode {
  INVITE_SUCCESS = 'INVITE_SUCCESS',
}
